/*
 * Create CALENDAR table with indizes on ID (PK), Category, User and Name
 */
CREATE TABLE "CALENDAR" (
  "ID"          INTEGER NOT NULL PRIMARY KEY ASC AUTOINCREMENT,
  "CATEGORY_ID" INTEGER NOT NULL,
  "USER_ID"     INTEGER NULL,
  "NAME"        TEXT    NOT NULL,
  "DATE"        TEXT    NOT NULL,
  "REMINDED"    INTEGER NOT NULL,
	
  FOREIGN KEY(CategoryID) REFERENCES CATEGORY(ID),
  FOREIGN KEY(UserID)     REFERENCES USER(ID)
);

CREATE INDEX IF NOT EXISTS "IDX_CATEGORY" ON "CALENDAR" ("CATEGORY_ID");
CREATE INDEX IF NOT EXISTS "IDX_USER"     ON "CALENDAR" ("USER_ID");
CREATE INDEX IF NOT EXISTS "IDX_DATE"     ON "CALENDAR" ("DATE");


/*
 * Create CATEGORY table with indizes on ID (PK), User and Name
 */
CREATE TABLE "CATEGORY" (
	"ID"      INTEGER NOT NULL PRIMARY KEY ASC,
	"USER_ID" INTEGER NULL,
	"NAME"    TEXT    NOT NULL,
	"COLOR"   TEXT    NOT NULL,

  FOREIGN KEY(UserID) REFERENCES USER(ID)
);

CREATE INDEX IF NOT EXISTS "IDX_USER" ON "CATEGORY" ("USER_ID");
CREATE INDEX IF NOT EXISTS "IDX_NAME" ON "CATEGORY" ("NAME");


/*
 * Create USER table with indizes on ID (PK) and Name
 */
CREATE TABLE "USER" (
	"ID"       INTEGER NOT NULL PRIMARY KEY ASC,
	"NAME"     TEXT    NOT NULL,
	"PASSWORD" TEXT    NOT NULL
);

CREATE INDEX IF NOT EXISTS "IDX_NAME" ON "CATEGORY" ("NAME");
